### ISSUE TITLE
ATOM Transaction Failure

### ISSUE THREAD

**Issue by mmfoster74** [airgap-it/airgap-wallet#128]
I have tried to undelegate and send my ATOM to another wallet but I keep receiving the same error message: Transaction broadcasting failed: Network error. This has not been an issue before as I have made ATOM transactions on 11/24/21 and 12/6/21, as well as undelegated/withdrew DOT on 12/25/21. What is causing this Network error and how do I fix it so that my ATOM is not stuck in my wallet forever?

**Comment by AndreasGassmann** [comment]
The cosmos network / node underwent an upgrade recently that changed the message format and is not backwards compatible. So the transaction format we use in AirGap is no longer valid and the node rejects it.

We have a fix ready for it and are currently testing it. We are planning to submit the update to the stores in the next few days.

Sorry for the inconvenience.

**Comment by AndreasGassmann** [comment]
This was solved shortly after the issue was opened.

**Comment by mmfoster74** [comment]
Now the transaction is not saying failed but the undelegation I attempted in January is not showing up in my transaction history. Almost 2 months later & my ATOM is still not available. Have those fixes been tested yet?
